apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
  namespace: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springlabels
  template:
    metadata:
      labels:
        app: springlabels
    spec:
      containers:
      - name: springcontainer
        image: naveenkuamr/spring-web-application:tag
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
        - name: MONGO_DB_USERNAME
          value: admin
        - name: MONGO_DB_PASSWORD
          value: admin@0208
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: login
spec:
  type: NodePort
  selector:
    app: springlabels
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
  namespace: login
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongocon
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin@0208
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  namespace: login
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
